[book]
authors = ["Anna"]
language = "en"
multilingual = false
src = "src"
title = "Heliosphere Documentation"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
cname = "docs.heliosphere.app"
git-repository-url = "https://github.com/heliosphere-xiv/docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/heliosphere-xiv/docs/edit/main/{path}"
